Script started on Tue 29 Apr 2014 10:19:52 PM EDT
theo@theo-VBox:~/Documents/spring-2014/11/c++$ cat threaded_array_sum.cpp 
/* threaded_array_sum.cpp sums the values in a file
 *  by reading them into an array and summing them there.
 *  It splits the work across several threads to increase performance.
 *
 * Begun by: Prof. Adams, for CS 214 at Calvin College.
 * Completed by:Charles Blum
 * Date:29 April 2014
 *
 * Usage: array_sum <inFileName>
 */

#include <iostream>     // cin, cout, etc
#include <fstream>      // ifstream, ofstream
#include <vector>       // vector
#include <cassert>      // assert()
#include <cstdlib>      // exit()
#include "NanoTimer.h"  // nanosecond timer
#include <iomanip>      // formatted output
#include <omp.h>	// OmpenMP
using namespace std;

void checkCommandLine(int argc);
void readFile(const string& fileName, vector<int>& v);
long sum(const vector<int>& v, unsigned numThreads);
void display(long total, const NanoTimer& nTimer);

int main(int argc, char** argv) {
   checkCommandLine(argc);
   vector<int> values;
   readFile( argv[1], values );
   long total;
   NanoTimer nTimer;
   nTimer.start();
   total = sum( values, atoi(argv[2]) );
   nTimer.stop();
   display(total, nTimer);
}

void checkCommandLine(int argc) {
   if (argc != 3) {
      cerr << "\nUsage: array_sum <fileName> <numThreads>\n\n";
      exit(1);
   }
}

long sum(const vector<int>& v, unsigned numThreads) {
   long result = 0;

   #pragma omp parallel for num_threads(numThreads) reduction(+ : result)
   for (unsigned i = 0; i < v.size(); i++) {
      result += v[i];
   }

   return result;
}


void readFile(const string& fileName, vector<int>& v) {
   ifstream fin( fileName.c_str() );
   assert( fin.is_open() );

   int number;
   fin >> number;
   v.reserve(number);
   while (true) {
      fin >> number;
      if ( fin.eof() ) break;
      v.push_back(number);
   }
   
   fin.close();
}

void display(long total , const NanoTimer& nTimer) {
   cout << "\nThe sum is " << total 
        << "\n and computing it took " 
        << fixed << showpoint << setprecision(9) 
        << nTimer 
        << " secs.\n" << endl;

}
theo@theo-VBox:~/Documents/spring-2014/11/c++$ make
make: Nothing to be done for `all'.
theo@theo-VBox:~/Documents/spring-2014/11/c++$ ./threaded_array_sum ../numbers/1 000000numbers.txt  1

The sum is 500869305
 and computing it took 0.004507556 secs.

theo@theo-VBox:~/Documents/spring-2014/11/c++$ ./threaded_array_sum ../numbers/10000000numbers.txt  1[K2

The sum is 500869305
 and computing it took 0.002616254 secs.

theo@theo-VBox:~/Documents/spring-2014/11/c++$ ./threaded_array_sum ../numbers/10000000numbers.txt  2[K4

The sum is 500869305
 and computing it took 0.002523225 secs.

theo@theo-VBox:~/Documents/spring-2014/11/c++$ exit

Script done on Tue 29 Apr 2014 10:20:30 PM EDT
