Script started on Tue 01 Apr 2014 09:39:36 PM EDT
]0;theo@theo-VBox: ~/Desktop/cs332/JCShelltheo@theo-VBox:~/Desktop/cs332/JCShell$  cd Debug/
]0;theo@theo-VBox: ~/Desktop/cs332/JCShell/Debugtheo@theo-VBox:~/Desktop/cs332/JCShell/Debug$ ./proj3 
/home/theo/Desktop/cs332/JCShell/Debug$ cd ../De	bug &
/home/theo/Desktop/cs332/JCShell/Debug$ ls -l &
backgrounded process - pid 5362
/home/theo/Desktop/cs332/JCShell/Debug$ total 1808
-rw-r--r-- 1 theo theo     70 Mar 17 22:27 CommandLine.d
-rw-r--r-- 1 theo theo 226032 Mar 17 22:27 CommandLine.o
-rw-r--r-- 1 theo theo    209 Mar 17 23:33 CommandLineTester.d
-rw-r--r-- 1 theo theo 169544 Mar 17 23:33 CommandLineTester.o
-rw-r--r-- 1 theo theo    141 Apr  1 21:31 JCShell.d
-rw-rw-r-- 1 theo theo 256768 Apr  1 21:31 JCShell.o
-rw-r--r-- 1 theo theo     42 Apr  1 21:31 Path.d
-rw-rw-r-- 1 theo theo 247512 Apr  1 21:31 Path.o
-rw-r--r-- 1 theo theo     50 Apr  1 21:31 Prompt.d
-rw-rw-r-- 1 theo theo  98544 Apr  1 21:31 Prompt.o
-rw-r--r-- 1 theo theo   1301 Mar 20 20:08 makefile
-rw-r--r-- 1 theo theo    231 Mar 12 19:21 objects.mk
-rwxrwxr-x 1 theo theo 665748 Apr  1 21:37 proj3
-rw-r--r-- 1 theo theo    134 Apr  1 21:31 shell.d
-rw-rw-r-- 1 theo theo 129720 Apr  1 21:31 shell.o
-rw-r--r-- 1 theo theo    526 Mar 20 20:08 sources.mk
-rw-r--r-- 1 theo theo    912 Mar 20 20:08 subdir.mk
clear
TERM environment variable not set.
/home/theo/Desktop/cs332/JCShell/Debug$ pwd
/home/theo/Desktop/cs332/JCShell/Debug
/home/theo/Desktop/cs332/JCShell/Debug$ emacs &
backgrounded process - pid 5365
/home/theo/Desktop/cs332/JCShell/Debug$ Please set the environment variable DISPLAY or TERM (see `tset').
ls
CommandLine.d	     JCShell.d	Prompt.d    proj3	subdir.mk
CommandLine.o	     JCShell.o	Prompt.o    shell.d
CommandLineTester.d  Path.d	makefile    shell.o
CommandLineTester.o  Path.o	objects.mk  sources.mk
/home/theo/Desktop/cs332/JCShell/Debug$ ^C
]0;theo@theo-VBox: ~/Desktop/cs332/JCShell/Debugtheo@theo-VBox:~/Desktop/cs332/JCShell/Debug$ exit

Script done on Tue 01 Apr 2014 09:41:07 PM EDT
