Script started on Thu 20 Feb 2014 09:21:13 AM EST
cab35@englebart:~/Documents/cs214/labs/lab03$ cat year_codes.cpp 
/* year_codes.cpp is a driver for function yearCode().
 * Begun by: Dr. Adams, for CS 214 at Calvin College.
 ****************************************************************/

#include <iostream>                      // interactive I/O
#include <string>                        // string class
using namespace std;

int yearCode(const string & year);

int main() {
  cout << "\nEnter your academic year: "; // prompt
  string year;
  cin >> year;                            // read year
  cout << yearCode(year) << endl;         // display its code
}


/***************************************************************
 * yearCode() converts an academic year into its integer code. *
 * Receive: year, a string.
 * PRE: year is one of {freshman, sophomore, junior, or senior}.
 * Return: the integer code corresponding to year.
 */

// REPLACE THIS LINE WITH THE DEFINITION OF yearCode()
int yearCode(const string & year){
  if ( year == "freshman" )
  {
    return 1;
  }
  else if ( year == "sophmore" )
  {
    return 2;
  }
  else if ( year == "junior" )
  {
    return 3;
  }
  else if ( year == "senior" )
  {
    return 4;
  }
  else
  {
    return 0;
  }
}
cab35@englebart:~/Documents/cs214/labs/lab03$ g++ -Wall year_codes.cpp -o cpp_year_codes 
cab35@englebart:~/Documents/cs214/labs/lab03$ g++ -Wall year_codes.cpp -o cpp_year_codes [24Pcat year_codes.cpp[Cvim[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cls[Kcd ~/Documents/cs214/labs/lab03[6@p year*[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cls[Kcd 03[3Plscp year* ~/Documents/cs214/labs/lab03[6Pd[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cls[Kvim year_codes.cpp cat[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[24@g++ -Wall year_codes.cpp -o cpp_year_codes[C[K./cpp_year_codes 

Enter your academic year: fesh   reshaman    man
1
cab35@englebart:~/Documents/cs214/labs/lab03$ ./cpp_year_codes 

Enter your academic year: hello world
0
cab35@englebart:~/Documents/cs214/labs/lab03$ ./cpp_year_codes 

Enter your academic year: senior
4
cab35@englebart:~/Documents/cs214/labs/lab03$ exit

Script done on Thu 20 Feb 2014 09:22:11 AM EST
