Script started on Thu 20 Feb 2014 10:04:53 AM EST
cab35@englebart:~/Documents/cs214/labs/lab03$ car[Kt year_codes.rb 
#! /usr/bin/ruby
# year_codes.rb translates an academic year into a numeric code
# Begun by: Dr. Nelesen, for CS 214 at Calvin College 
################################################################

# Input:  The name of an academic year
# Precondition: The academic year is a string with a value of freshman, 
#   sophomore, junior or senior
# Output: The corresponding integer code for the given academic year

def yearCode year
  if year =~ /freshman/ then 1
  elsif year =~ /sophmore/ then  2
  elsif year =~ /junior/ then 3
  elsif year =~ /senior/ then 4
  else 0
  end
end

if __FILE__ == $0
   print "Enter the year: "
   year = gets
   print "Numeric code is: "
   puts yearCode(year)
end

cab35@englebart:~/Documents/cs214/labs/lab03$ ruby year_codes.rb 
Enter the year: hello
Numeric code is: 0
cab35@englebart:~/Documents/cs214/labs/lab03$ ruby year_codes.rb 
Enter the year: freshamn   man
Numeric code is: 1
cab35@englebart:~/Documents/cs214/labs/lab03$ ruby year_codes.rb 
Enter the year: junior
Numeric code is: 3
cab35@englebart:~/Documents/cs214/labs/lab03$ exit

Script done on Thu 20 Feb 2014 10:05:20 AM EST
