Script started on Tue 04 Mar 2014 03:55:17 PM EST
]0;theo@theo-VBox: ~/Desktop/project04theo@theo-VBox:~/Desktop/project04$ cat factorial.rb 
#! /usr/bin/ruby
# factorial.rb displays the factorial of a number
#
# Begun by: Charles Blum, for CS 214 at Calvin College.
# Begun on: 4 March 2014
#
# Input:  n, an integer
# Precondition: n is >= 0
# Output: The factorial of n 

def comp_factorial(n)
  f = 1
  for i in 1..n
    f *= i
  end
  f
end

if __FILE__ == $0
  print "This program calculates the factorial of a number:"
  print "Enter a number n:"
  n = gets.chomp.to_i

  puts "#{n}! = #{comp_factorial(n)}"
end

]0;theo@theo-VBox: ~/Desktop/project04theo@theo-VBox:~/Desktop/project04$ ruby factorial.rb
This program calculates the factorial of a number:Enter a number n:5
5! = 120
]0;theo@theo-VBox: ~/Desktop/project04theo@theo-VBox:~/Desktop/project04$ ruby factorial.rb
This program calculates the factorial of a number:Enter a number n:6
6! = 720
]0;theo@theo-VBox: ~/Desktop/project04theo@theo-VBox:~/Desktop/project04$ ruby factorial.rb
This program calculates the factorial of a number:Enter a number n:10
10! = 3628800
]0;theo@theo-VBox: ~/Desktop/project04theo@theo-VBox:~/Desktop/project04$ exit

Script done on Tue 04 Mar 2014 03:55:48 PM EST
