Script started on Mon 14 Apr 2014 07:42:49 AM EDT
theo@theo-VBox:~/Desktop/08/c++$ cat NA[Kame.h Name.cpp N[Knamer.cpp
/* Name.h declares class Name.
 *
 * Begun by: Dr. Adams, CS 214 at Calvin College.
 * Completed by:Charles Blum
 * Date: 13 April 2014
 */

#include <string>          // string
using namespace std;

class Name {
public:                          // interface functions
   Name(const string & first, const string & middle, const string &
last);
   void print(ostream & out);
   string getFirst() const;
   string getMiddle() const;
   string getLast() const;
   string getFullName() const;

private:
   string myFirst,
          myMiddle,
          myLast;
};
/* Name.cpp defines Name operations.
 *
 * Begun by: Dr. Adams, CS 214 at Calvin College.
 * Completed by: Charles Blum
 * Date: 13 April 2014
 */

#include <iostream>        // istream, ostream
#include <string>
#include "Name.h"
using namespace std;

/**************************************************
* Name constructs a name from three strings.      *
* Receive: first, middle and last, three strings. *
* Return: the triplet (first middle last).        *
***************************************************/
Name::Name(const string & first, const string & middle, const string & last)
{
   myFirst = first;
   myMiddle = middle;
   myLast = last;
}


/***************************************************
 * getFirst() extracts the first name of a Name object. 
 * Return: myFirst.                                
 ***************************************************/
string Name::getFirst() const {
   return myFirst;
}


/*****************************************************
 * getMiddle() extracts the middle name of a Name object. 
 * Return: myMiddle.                                 
 *****************************************************/
string Name::getMiddle() const {
   return myMiddle;
}


/**************************************************
 * getLast() extracts the last name of a Name object.  
 * Return: myLast.                                
 **************************************************/
string Name::getLast() const {
   return myLast;
}


/***************************************************
 * getFullName() returns a full name in F-M-L order.  
 * Return: myFirst, myMiddle, myLast.           
 ***************************************************/
string Name::getFullName() const {
   return myFirst + ' ' + myMiddle + ' ' + myLast;
}

/****************************************************
 * print() displays a Name object.                    
 * Receive: out, the name of a stream.              
 * Output: the strings in theName to buffer.        
 * POST: out contains myFirst, myMiddle and myLast. 
 ****************************************************/
void Name::print(ostream & out) {
   out << myFirst << ' ' << myMiddle << ' ' << myLast;
}
/* namer.cpp implements and tests class Name.
 *
 * Begun by: Dr. Adams, for CS 214 at Calvin College.
 * Completed by:
 * Date:
 *****************************************************/

#include <iostream>        // istream, ostream
#include <cassert>
#include "Name.h"
using namespace std;

/******************************************
 * a simple driver to test our Name type. *
 ******************************************/
int main()
{
  Name aName("John", "Paul", "Jones");
  
  assert( aName.getMiddle() == "Paul" );
  assert( aName.getLast() == "Jones" );
  assert( aName.getFullName() == "John Paul Jones" );
  
  aName.print(cout);  cout << endl;
  cout << "All tests passed!\n";
}

theo@theo-VBox:~/Desktop/08/c++$ make
make: `namer' is up to date.
theo@theo-VBox:~/Desktop/08/c++$ ./namer 
John Paul Jones
All tests passed!
theo@theo-VBox:~/Desktop/08/c++$ exit

Script done on Mon 14 Apr 2014 07:43:07 AM EDT
