Script started on Sun 27 Apr 2014 11:38:22 AM EDT
]0;theo@theo-VBox: ~/Documents/spring-2014/09/rubytheo@theo-VBox:~/Documents/spring-2014/09/ruby$ cat List.rb max.rb 
# List.rb implements a linked list structure in Ruby.
#
# Begun by: Dr. Adams, for CS 214 at Calvin College.
# Completed by:Charles Blum
# Date:28 April 2014
#######################################################

require 'test/unit/assertions'
include Test::Unit::Assertions

class List

   # initialize a List to be empty
   # Postcondition: first == nil and last == nil and length == 0
   def initialize
      @first, @last, @length  = nil, nil, 0
   end #init

   # create reader method for length
   def getLength
      @length
   end #getLength

   # Am I empty?
   # Return: length == 0
   def empty?
      @length == 0
   end #empty?
  
   # append a value to me
   # Receive: value, the item to be appended
   # Postcondition: my last item is value and
   #                 my length is one more than it was
   def append(value)
      newNode = Node.new(value, nil)

      if empty?
         @first = newNode
      else
         @last.next = newNode      
      end #if

      @last = newNode
      @length += 1
      self
   end #append


   # print my items
   # Postcondition: my items have been displayed to the screen
   def print 
      temp = @first
      while !temp.nil?
	 printf " #{temp.value}"
	 temp = temp.next
      end #while
   end #print

   # find my maximum item
   # Return: my maximum item
   def max
      temp = @first
      maxValue = -999999
      while !temp.nil?
	 if temp.value > maxValue
	    maxValue = temp.value
 	 end #if
	 temp = temp.next
      end #while
      maxValue
   end #max
   
   # find the index of nubmer 
   # Return: the index of number
   def getIndex(number)
      temp = @first
      indexOf = 0
      realIndex = -1
      while !temp.nil?
	if temp.value == number
	   realIndex = indexOf 
 	end #if
	temp = temp.next
	indexOf += 1
      end #while
      realIndex
   end #getIndex

   class Node
      def initialize(item, link)
         @value = item
 	 @next = link
      end #init

      attr_reader :value
      attr_accessor :next
   end #Node

end #List

# max.rb tests a Ruby linked list.
#
# Begun by: Dr. Adams for CS 214 at Calvin College.
# Completed by: Charles Blum
# Date: 21 April 2014

require 'List'

list1 = List.new
list2 = List.new
list3 = List.new
list4 = List.new

list1.append(99).append(88).append(77).append(66).append(55)
list2.append(55).append(66).append(77).append(88).append(99)
list3.append(55).append(77).append(99).append(88).append(66)
list4.append(55).append(44).append(33).append(22).append(11)

list1.print 
puts
puts "Maximum of list1: #{list1.max}"
puts "The index of 99 is: #{list1.getIndex(99)}"

list2.print 
puts
puts "Maximum of list2: #{list2.max}"
puts "The index of 99 is: #{list2.getIndex(99)}"

list3.print 
puts
puts "Maximum of list3: #{list3.max}"
puts "The index of 99 is: #{list3.getIndex(99)}"

list4.print 
puts
puts "Maximum of list43: #{list4.max}"
puts "The index of 99 is: #{list4.getIndex(99)}"

]0;theo@theo-VBox: ~/Documents/spring-2014/09/rubytheo@theo-VBox:~/Documents/spring-2014/09/ruby$ ruby max.rb 
 99 88 77 66 55
Maximum of list1: 99
The index of 99 is: 0
 55 66 77 88 99
Maximum of list2: 99
The index of 99 is: 4
 55 77 99 88 66
Maximum of list3: 99
The index of 99 is: 2
 55 44 33 22 11
Maximum of list43: 55
The index of 99 is: -1
]0;theo@theo-VBox: ~/Documents/spring-2014/09/rubytheo@theo-VBox:~/Documents/spring-2014/09/ruby$ exit

Script done on Sun 27 Apr 2014 11:38:32 AM EDT
