Script started on Thu 27 Feb 2014 09:14:11 AM EST
cab35@englebart:~/Documents/cs214/labs/lab04$ cat log_table.cpp
/* log_table.cpp displays a table of logarithms.
 *
 * Input: start, stop and increment, three doubles.
 * PRE: start < stop && increment > 0.
 * Output: A table of logarithms from start to stop,
 *         with increment as the step value.
 * Begun by: Adams, for CS 214 at Calvin College.
 * Completed by:
 ********************************************************/

#include <iostream>    // cin, cout, <<, >>
#include <cassert>     // assert()
#include <cmath>       // log10()
using namespace std;

int main() {
  cout << "\nTo display a table of logarithms,"
       << "\n enter the start, stop and increment values: ";
  double start, stop, increment;
  cin >> start >> stop >> increment;
  
  assert(increment > 0);
  
  for ( double i = start; i <= stop; i += increment )
    cout << "\nThe logarithm of " << i << " is\t " << log10(i) << flush;
  cout << endl;
}

cab35@englebart:~/Documents/cs214/labs/lab04$ g++ -Q[KWall log_table.cpp -o cpp_log_table 
cab35@englebart:~/Documents/cs214/labs/lab04$ ./lo[K[Kcpp_log_table 

To display a table of logarithms,
 enter the start, stop and increment values: 1 10 0.5

The logarithm of 1 is	 0
The logarithm of 1.5 is	 0.176091
The logarithm of 2 is	 0.30103
The logarithm of 2.5 is	 0.39794
The logarithm of 3 is	 0.477121
The logarithm of 3.5 is	 0.544068
The logarithm of 4 is	 0.60206
The logarithm of 4.5 is	 0.653213
The logarithm of 5 is	 0.69897
The logarithm of 5.5 is	 0.740363
The logarithm of 6 is	 0.778151
The logarithm of 6.5 is	 0.812913
The logarithm of 7 is	 0.845098
The logarithm of 7.5 is	 0.875061
The logarithm of 8 is	 0.90309
The logarithm of 8.5 is	 0.929419
The logarithm of 9 is	 0.954243
The logarithm of 9.5 is	 0.977724
The logarithm of 10 is	 1
cab35@englebart:~/Documents/cs214/labs/lab04$ exit

Script done on Thu 27 Feb 2014 09:14:43 AM EST
